# PLEASE REFER TO OFFICIAL: https://github.com/liftoff/GateOne/tree/master/docker
#
# BUILD this with
#   docker build -t bennyli/rpi-gateone .
# and RUN with
#   docker run -d -p 127.0.0.1:9443:443 --restart=always --name gateone bennyli/rpi-gateone
# Autostart:
#   https://docs.docker.com/articles/host_integration/
